#
# SPDX-License-Identifier: Apache-2.0
#

steps:
  - script: ./startFabric.sh java
    workingDirectory: baas
    displayName: Start Fabric
  - script: retry -- mvn dependency:go-offline
    workingDirectory: baas/java
    displayName: Install baas Application Dependencies
  - script: mvn test
    workingDirectory: baas/java
    displayName: Run baas Application
