#
# SPDX-License-Identifier: Apache-2.0
#

steps:
  - script: ./startFabric.sh typescript
    workingDirectory: baas
    displayName: Start Fabric
  - script: retry -- npm install
    workingDirectory: baas/typescript
    displayName: Install baas Application Dependencies
  - script: npm run build
    workingDirectory: baas/typescript
    displayName: Build baas application
  - script: |
      set -ex
      node dist/enrollAdmin
      node dist/registerUser
      node dist/invoke
      node dist/query
    workingDirectory: baas/typescript
    displayName: Run baas Application
