#
# SPDX-License-Identifier: Apache-2.0
#

steps:
  - script: ./startFabric.sh go
    workingDirectory: baas
    displayName: Start Fabric
  - task: GoTool@0
    displayName: 'Use Go 1.14.2'
    inputs:
      version: '1.14.2'
  - task: Go@0
    displayName: 'go build'
    inputs:
      command: build
      arguments: '-o "baas"'
      workingDirectory: baas/go
  - script: DISCOVERY_AS_LOCALHOST=TRUE ./baas
    workingDirectory: baas/go
    displayName: Run baas Application
