#
# SPDX-License-Identifier: Apache-2.0
#

steps:
  - script: ./startFabric.sh javascript
    workingDirectory: baas
    displayName: Start Fabric
  - script: |
      retry -- npm install
      npm ls
    workingDirectory: baas/javascript
    displayName: Install baas Application Dependencies
  - script: |
      set -ex
      node enrollAdmin
      node registerUser
      node invoke
      node query
    workingDirectory: baas/javascript
    displayName: Run baas Application
